import {
  describe, it, expect 
} from 'vitest'
import {
  formatReplyBody, respondToFeedbackInputSchema 
} from './feedback-response'

describe('formatReplyBody', () => {
  it('formats fixed action with message', () => {
    const result = formatReplyBody('fixed', 'Applied the suggested change')

    expect(result).toContain('✅ **Fixed**')
    expect(result).toContain('Applied the suggested change')
    expect(result).toContain('Generated by Claude Code')
  })

  it('formats rejected action with message', () => {
    const result = formatReplyBody('rejected', 'This is intentional design')

    expect(result).toContain('❌ **Rejected**')
    expect(result).toContain('This is intentional design')
    expect(result).toContain('Generated by Claude Code')
  })
})

describe('respondToFeedbackInputSchema', () => {
  it('validates valid fixed input', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'fixed',
      message: 'Done',
    }

    const result = respondToFeedbackInputSchema.parse(input)

    expect(result.action).toStrictEqual('fixed')
  })

  it('validates valid rejected input', () => {
    const input = {
      threadId: 'PRRT_456',
      action: 'rejected',
      message: 'Not applicable',
    }

    const result = respondToFeedbackInputSchema.parse(input)

    expect(result.action).toStrictEqual('rejected')
  })

  it('rejects empty threadId', () => {
    const input = {
      threadId: '',
      action: 'fixed',
      message: 'Done',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('threadId is required')
  })

  it('rejects empty message', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'fixed',
      message: '',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('message is required')
  })

  it('rejects invalid action', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'invalid',
      message: 'Done',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('Invalid option')
  })
})
