import { z } from 'zod'

export const responseActionSchema = z.enum(['fixed', 'rejected'])
export type ResponseAction = z.infer<typeof responseActionSchema>

export const respondToFeedbackInputSchema = z.object({
  threadId: z.string().min(1, { message: 'threadId is required' }),
  action: responseActionSchema,
  message: z.string().min(1, { message: 'message is required' }),
})
export type RespondToFeedbackInput = z.infer<typeof respondToFeedbackInputSchema>

const respondToFeedbackOutputSchema = z.object({
  success: z.boolean(),
  threadId: z.string(),
  action: responseActionSchema,
  error: z.string().optional(),
})
export type RespondToFeedbackOutput = z.infer<typeof respondToFeedbackOutputSchema>

const GENERATED_BY_SUFFIX = '\n\n---\n*Generated by Claude Code*'

export function formatReplyBody(action: ResponseAction, message: string): string {
  const prefix = action === 'fixed' ? '✅ **Fixed**' : '❌ **Rejected**'
  return `${prefix}: ${message}${GENERATED_BY_SUFFIX}`
}
