import type { EdgeDefinition } from './architecture-evolution-types'

export const EDGE_DEFINITIONS: readonly EdgeDefinition[] = [
  {
    id: 'web-a-read',
    source: 'website',
    target: 'service-a',
    label: 'GET /orders',
    subtitle: 'Website -> Query API',
    description: 'Website reads the orders list from the Orders Service A query API.',
    sourcePortLabel: 'Website client',
    targetPortLabel: 'Query API',
    kind: 'query',
    sourceHandle: 'bottom-left-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 18,
      borderRadius: 14,
      stepPosition: 0.46,
    },
  },
  {
    id: 'web-b-read',
    source: 'website',
    target: 'service-b',
    label: 'GET /orders',
    subtitle: 'Website -> Query API',
    description: 'Website also reads orders from the Orders Service B query API during migration.',
    sourcePortLabel: 'Website client',
    targetPortLabel: 'Query API',
    kind: 'query',
    sourceHandle: 'bottom-right-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 26,
      borderRadius: 14,
      stepPosition: 0.52,
    },
  },
  {
    id: 'mobile-a-read',
    source: 'mobile',
    target: 'service-a',
    label: 'GET /orders',
    subtitle: 'Mobile -> Query API',
    description:
      'Mobile app reads orders from the Orders Service A query API after the final consumer migration.',
    sourcePortLabel: 'Mobile client',
    targetPortLabel: 'Query API',
    kind: 'query',
    sourceHandle: 'bottom-left-source',
    targetHandle: 'top-right-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 42,
      borderRadius: 16,
      stepPosition: 0.34,
    },
  },
  {
    id: 'mobile-b-read',
    source: 'mobile',
    target: 'service-b',
    label: 'GET /orders',
    subtitle: 'Mobile -> Query API',
    description:
      'Mobile app reads orders from the Orders Service B query API before the service is removed.',
    sourcePortLabel: 'Mobile client',
    targetPortLabel: 'Query API',
    kind: 'query',
    sourceHandle: 'bottom-left-source',
    targetHandle: 'top-right-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 18,
      borderRadius: 14,
      stepPosition: 0.48,
    },
  },
  {
    id: 'mobile-c-read',
    source: 'mobile',
    target: 'service-c',
    label: 'GET /orders',
    subtitle: 'Mobile -> Query API',
    description:
      'Mobile app reads orders from the Orders Service C query API until the final cutover to A.',
    sourcePortLabel: 'Mobile client',
    targetPortLabel: 'Query API',
    kind: 'query',
    sourceHandle: 'bottom-right-source',
    targetHandle: 'top-right-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 18,
      borderRadius: 14,
      stepPosition: 0.46,
    },
  },
  {
    id: 'a-db-a-write',
    source: 'service-a',
    target: 'db-a',
    label: 'Persist order',
    subtitle: 'POST /orders write path',
    description: 'Orders Service A persists the accepted order in Orders DB A.',
    sourcePortLabel: 'POST /orders',
    targetPortLabel: 'Orders table',
    kind: 'write',
    sourceHandle: 'bottom-middle-source',
    targetHandle: 'top-middle-target',
    type: 'straight',
  },
  {
    id: 'b-db-b-write',
    source: 'service-b',
    target: 'db-b',
    label: 'Persist order',
    subtitle: 'POST /orders write path',
    description:
      'Orders Service B persists the accepted order in Orders DB B while its write API still exists.',
    sourcePortLabel: 'POST /orders',
    targetPortLabel: 'Orders table',
    kind: 'write',
    sourceHandle: 'bottom-middle-source',
    targetHandle: 'top-middle-target',
    type: 'straight',
  },
  {
    id: 'c-db-c-write',
    source: 'service-c',
    target: 'db-c',
    label: 'Persist order',
    subtitle: 'POST /orders write path',
    description:
      'Orders Service C persists the accepted order in Orders DB C while its write API still exists.',
    sourcePortLabel: 'POST /orders',
    targetPortLabel: 'Orders table',
    kind: 'write',
    sourceHandle: 'bottom-middle-source',
    targetHandle: 'top-middle-target',
    type: 'straight',
  },
  {
    id: 'a-db-b-write',
    source: 'service-a',
    target: 'db-b',
    label: 'Replicate order',
    subtitle: 'Dual write to replica',
    description:
      'Orders Service A also writes the same order record into Orders DB B during the B migration.',
    sourcePortLabel: 'Migration write path',
    targetPortLabel: 'Orders table replica',
    kind: 'write',
    sourceHandle: 'bottom-right-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 20,
      borderRadius: 18,
      stepPosition: 0.68,
    },
  },
  {
    id: 'a-db-c-write',
    source: 'service-a',
    target: 'db-c',
    label: 'Replicate order',
    subtitle: 'Dual write to replica',
    description:
      'Orders Service A also writes the same order record into Orders DB C during the C migration.',
    sourcePortLabel: 'Migration write path',
    targetPortLabel: 'Orders table replica',
    kind: 'write',
    sourceHandle: 'bottom-right-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 28,
      borderRadius: 18,
      stepPosition: 0.52,
    },
  },
  {
    id: 'a-b-event',
    source: 'service-a',
    target: 'service-b',
    label: 'OrderPlaced',
    subtitle: 'Domain event replication',
    description:
      'Orders Service A publishes OrderPlaced so Orders Service B can mirror the new order.',
    sourcePortLabel: 'Event publisher',
    targetPortLabel: 'Event consumer',
    kind: 'event',
    sourceHandle: 'top-right-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 28,
      borderRadius: 18,
      stepPosition: 0.5,
    },
  },
  {
    id: 'a-c-event',
    source: 'service-a',
    target: 'service-c',
    label: 'OrderPlaced',
    subtitle: 'Domain event replication',
    description:
      'Orders Service A publishes OrderPlaced so Orders Service C can mirror the new order.',
    sourcePortLabel: 'Event publisher',
    targetPortLabel: 'Event consumer',
    kind: 'event',
    sourceHandle: 'top-middle-source',
    targetHandle: 'top-middle-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 92,
      borderRadius: 22,
      stepPosition: 0.5,
    },
  },
  {
    id: 'b-c-event',
    source: 'service-b',
    target: 'service-c',
    label: 'OrderPlaced',
    subtitle: 'Domain event replication',
    description:
      'Orders Service B publishes OrderPlaced so Orders Service C can mirror the new order.',
    sourcePortLabel: 'Event publisher',
    targetPortLabel: 'Event consumer',
    kind: 'event',
    sourceHandle: 'top-right-source',
    targetHandle: 'top-left-target',
    type: 'smoothstep',
    pathOptions: {
      offset: 28,
      borderRadius: 18,
      stepPosition: 0.5,
    },
  },
] as const
