import type {
  InvocationGuideEntry,
  SubdomainGuideEntry,
  UseCaseGuideEntry,
} from './domain-guide-source'

export function renderDomainGuide(subdomains: readonly SubdomainGuideEntry[]): string {
  return [
    '# Domain guide',
    '',
    '> This file is generated by `./build-domain-guide.sh`. Do not edit it directly.',
    '',
    'This guide is a map of the currently implemented domain model. Start discovery here, then inspect the relevant code and tests. The guide is evidence of the current model, not proof that the model is correct.',
    '',
    'For shared domain language, use the [domain glossary](../domain-terminology/contextive/definitions.glossary.yml). This generator does not interpret or copy glossary entries.',
    '',
    '## Contents',
    '',
    '- [Applications](#applications)',
    '- [Subdomain overview](#subdomain-overview)',
    '- [Subdomains](#subdomains)',
    ...subdomains.map((subdomain) => `  - [\`${subdomain.name}\`](#${subdomain.name})`),
    '',
    '## Subdomain overview',
    '',
    '| Subdomain | Purpose | Domain packages | Aggregates | Command use cases | Query use cases | CLI use cases |',
    '| --- | --- | --- | --- | ---: | ---: | ---: |',
    ...subdomains.map(renderSubdomainOverview),
    '',
    '## Applications',
    '',
    '- `apps/cli`: Command line application that exposes use cases from multiple subdomains. Detailed CLI use case mappings appear under each subdomain.',
    '- `apps/eclair`: Web application for browsing Rivière architecture graphs.',
    '- `apps/docs`: Documentation site for Living Architecture and Rivière.',
    '',
    '## Subdomains',
    '',
    ...subdomains.flatMap(renderSubdomain),
  ].join('\n')
}

function renderSubdomain(subdomain: SubdomainGuideEntry): readonly string[] {
  const commands = subdomain.useCases.filter((useCase) => useCase.role === 'command-use-case')
  const queries = subdomain.useCases.filter((useCase) => useCase.role === 'query-model-use-case')
  const cliUseCases = subdomain.useCases.filter((useCase) => useCase.availableInCli)
  return [
    `### \`${subdomain.name}\``,
    '',
    subdomain.description,
    '',
    ...renderDomainPackages(subdomain),
    '',
    '#### Aggregates',
    '',
    ...renderAggregates(subdomain),
    '',
    '#### Supported use cases',
    '',
    '##### Commands',
    '',
    ...renderUseCases(commands),
    '',
    '##### Queries',
    '',
    ...renderUseCases(queries),
    '',
    '#### CLI use cases',
    '',
    ...(cliUseCases.length === 0
      ? ['_No use cases from this subdomain are currently exposed through `apps/cli`._']
      : cliUseCases.map((useCase) => `- \`${useCase.name}\``)),
    '',
  ]
}

function renderSubdomainOverview(subdomain: SubdomainGuideEntry): string {
  const commands = subdomain.useCases.filter((useCase) => useCase.role === 'command-use-case')
  const queries = subdomain.useCases.filter((useCase) => useCase.role === 'query-model-use-case')
  const cliUseCases = subdomain.useCases.filter((useCase) => useCase.availableInCli)
  const aggregates =
    subdomain.aggregates.length === 0
      ? '_None declared_'
      : subdomain.aggregates.map((aggregate) => `\`${aggregate.name}\``).join(', ')
  const domainPackages = renderInlineDomainPackages(subdomain)
  return `| [\`${subdomain.name}\`](#${subdomain.name}) | ${escapeTableCell(subdomain.description)} | ${domainPackages} | ${aggregates} | ${commands.length} | ${queries.length} | ${cliUseCases.length} |`
}

function renderDomainPackages(subdomain: SubdomainGuideEntry): readonly string[] {
  return [
    ...(subdomain.domainModelPackageName === undefined
      ? []
      : [`Domain model package: \`${subdomain.domainModelPackageName}\``]),
    ...(subdomain.publishedLanguagePackageName === undefined
      ? []
      : [`Published language package: \`${subdomain.publishedLanguagePackageName}\``]),
  ]
}

function renderInlineDomainPackages(subdomain: SubdomainGuideEntry): string {
  return [
    ...(subdomain.domainModelPackageName === undefined
      ? []
      : [`domain model: \`${subdomain.domainModelPackageName}\``]),
    ...(subdomain.publishedLanguagePackageName === undefined
      ? []
      : [`published language: \`${subdomain.publishedLanguagePackageName}\``]),
  ].join('<br>')
}

function escapeTableCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function renderAggregates(subdomain: SubdomainGuideEntry): readonly string[] {
  if (subdomain.domainModelPackageName === undefined) {
    return ['_This subdomain currently exposes published language only._']
  }
  if (subdomain.aggregates.length === 0) {
    return ['_No aggregates are currently declared._']
  }
  return subdomain.aggregates.flatMap((aggregate) => [
    `- \`${aggregate.name}\``,
    ...(aggregate.operations.length === 0
      ? ['  - _No public methods are currently declared._']
      : aggregate.operations.map((operation) => `  - \`${operation}\``)),
  ])
}

function renderUseCases(useCases: readonly UseCaseGuideEntry[]): readonly string[] {
  if (useCases.length === 0) {
    return ['_None._']
  }
  return useCases.flatMap((useCase) => [
    `- \`${useCase.name}\``,
    ...useCase.invocations.map((invocation) => `  - ${renderInvocation(invocation)}`),
  ])
}

function renderInvocation(invocation: InvocationGuideEntry): string {
  const role = invocation.role === 'aggregate' ? 'aggregate' : 'domain service'
  const operation =
    invocation.concept === invocation.operation
      ? invocation.operation
      : `${invocation.concept}.${invocation.operation}`
  return `Invokes ${role} operation \`${operation}\``
}
